name: Auto Update Dates

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Update Dates
        run: |
          # Update index.html
          sed -i "s/Documentation Updated: .*/Documentation Updated: $(date +'%B %d, %Y')/" index.html
          # Update README.md
          sed -i "s/Documentation Last Updated: .*/Documentation Last Updated: $(date +'%B %d, %Y')/" README.md
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "Auto-update dates" || exit 0
          git push
