name: Update Timestamps

on:
  push:
    paths:
      - 'index.html'  # Only trigger when index.html changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get date from index.html and update README
        run: |
          # Extract date from index.html and update README.md
          DATE=$(grep -o "Last Updated: .*" index.html | cut -d ":" -f2 | xargs)
          sed -i "s/Last Updated:.*$/Last Updated:$DATE/" README.md
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README timestamp to match index.html"
          git push
