name: Update Timestamps

on:
  push:
    paths:
      - 'index.html'

permissions:
  contents: write
  actions: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get date from index.html and update README
        run: |
          # Extract date from index.html (looking for the exact format)
          INDEX_DATE=$(grep "Last Updated:" index.html | sed 's/.*Last Updated: \(.*\)<\/p>/\1/')
          if [ ! -z "$INDEX_DATE" ]; then
            # Update README.md with exact format match
            sed -i "s/Last Updated: .*$/Last Updated: $INDEX_DATE/" README.md
          else
            echo "Date not found in index.html"
            exit 1
          fi
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README timestamp to match index.html"
          git push
